# Generated by Django 4.0.4 on 2022-05-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_designer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='berries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cake_designer.berry', verbose_name='Ягоды'),
        ),
    ]
