# Generated by Django 4.0.4 on 2022-05-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_designer', '0002_alter_order_berries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cake_designer.decoration', verbose_name='Декор'),
        ),
    ]
