# Generated by Django 4.0.4 on 2022-05-04 13:58

from django.db import migrations
import json


def inject_cake_params(apps, schema_editor):
    Form = apps.get_model('cake_designer', 'Form')
    Topping = apps.get_model('cake_designer', 'Topping')
    Berry = apps.get_model('cake_designer', 'Berry')
    Decoration = apps.get_model('cake_designer', 'Decoration')

    with open('default_data.json', 'r') as default_data:
        cake_options = json.load(default_data).get("cake_options")

        for num, form in enumerate(cake_options.get('forms')):
            Form.objects.get_or_create(num=num + 1, title=form)

        for num, topping in enumerate(cake_options.get('toppings')):
            Topping.objects.get_or_create(num=num + 1, title=topping)

        for num, berry in enumerate(cake_options.get('berries')):
            Berry.objects.get_or_create(num=num + 1, title=berry)

        for num, decoration in enumerate(cake_options.get('decorations')):
            Decoration.objects.get_or_create(num=num + 1, title=decoration)






class Migration(migrations.Migration):

    dependencies = [
        ('cake_designer', '0003_alter_order_decoration'),
    ]

    operations = [
        migrations.RunPython(inject_cake_params)
    ]
