# Generated by Django 4.0.4 on 2022-05-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_designer', '0004_insert_default_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='cake_designer.delivery', verbose_name='Параметры доставки'),
        ),
    ]
