# Generated by Django 4.0.4 on 2022-05-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_designer', '0005_remove_customer_delivery_order_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(max_length=100, verbose_name='Which site sent the traffic')),
                ('utm_medium', models.CharField(max_length=100, verbose_name='Type of link')),
                ('utm_campaign', models.CharField(max_length=100, verbose_name='Аdvertising company')),
                ('utm_content', models.CharField(default=None, max_length=100, null=True, verbose_name='Content')),
                ('utm_term', models.CharField(default=None, max_length=100, null=True, verbose_name='Searching terms')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='utm',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cake_designer.utm', verbose_name='UTM'),
        ),
    ]
