# Generated by Django 4.0.4 on 2022-05-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_designer', '0006_delivery_status_alter_delivery_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('number', models.SmallIntegerField(verbose_name='Номинал')),
                ('is_valid', models.BooleanField(verbose_name='Активен')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promo_cost',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='С учетом скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cake_designer.promo', verbose_name='Промокод'),
        ),
    ]
