# Generated by Django 4.0.4 on 2022-05-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_designer', '0006_utm_order_utm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utm',
            old_name='utm_campaign',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='utm',
            old_name='utm_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='utm',
            old_name='utm_medium',
            new_name='medium',
        ),
        migrations.RenameField(
            model_name='utm',
            old_name='utm_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='utm',
            old_name='utm_term',
            new_name='term',
        ),
    ]
