# Generated by Django 4.0.4 on 2022-05-11 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_designer', '0007_promo_order_promo_cost_order_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='', editable=False, max_length=36, validators=[django.core.validators.MinLengthValidator(36)], verbose_name='Номер оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
    ]
